FROM python:3.12-slim
WORKDIR /app
COPY requirements-frontend.txt .
ENV PIP_INDEX_URL=https://pypi.sankuai.com/simple
RUN pip install -r requirements-frontend.txt --no-cache-dir --retries 10
COPY frontend/app.py ./app.py
EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]